---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: data
  labels:
    app: rabbitmq
spec:
  ports:
    - name: rabbitmq
      port: 5672
    - name: ui
      port: 15672
      targetPort: 15672
      nodePort: 32104
    - name: exporter
      port: 15692
      targetPort: 15692
  selector:
    app: rabbitmq
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq-pod
  namespace: data
  labels:
    app: rabbitmq
spec:
  containers:
    - name: rabbitmq-cont
      image: rabbitmq:management
      imagePullPolicy: Always
      ports:
        - protocol: TCP
          containerPort: 5672
      volumeMounts:
        - mountPath: "/var/lib/rabbitmq"
          name: rabbitmq-storage
      livenessProbe:
        exec:
          command: ["rabbitmq-diagnostics", "ping"]
        initialDelaySeconds: 120
      readinessProbe:
        exec:
          command: ["rabbitmq-diagnostics", "ping"]
        initialDelaySeconds: 30
        periodSeconds: 2
  volumes:
    - name: rabbitmq-storage
      persistentVolumeClaim:
        claimName: local-disk-rabbitmq-claim

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-disk-rabbitmq-claim
  namespace: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
