---
apiVersion: v1
kind: Namespace
metadata:
  name: monitor
  labels:
    name: monitor
---
apiVersion: v1
kind: Namespace
metadata:
  name: service
  labels:
    name: service
---
apiVersion: v1
kind: Namespace
metadata:
  name: data
  labels:
    name: data
---
apiVersion: v1
kind: Namespace
metadata:
  name: ui
  labels:
    name: ui
---
apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    name: test
