---
apiVersion: v1
kind: Secret
metadata:
  name: secret-config
  namespace: data
type: Opaque
data:
  postgres.user: cG9zdGdyZXMK
  postgres.password: cG9zdGdyZXMK

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-config
  namespace: service
type: Opaque
data:
  postgres.user: cG9zdGdyZXMK
  postgres.password: cG9zdGdyZXMK

---
# To encode -> echo postgres | base64 -
# To decode -> echo cG9zdGdyZXMK | base64 -D -
