apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: service
spec:
  limits:
  - default:
      cpu: 1
      memory: 768Mi
    defaultRequest:
      cpu: 0.25
      memory: 256Mi
    type: Container
