############################################################################
# Copyright 2020 Anurag Yadav (anurag.yadav@newtechways.com)               #
#                                                                          #
# Licensed under the Apache License, Version 2.0 (the "License");          #
# you may not use this file except in compliance with the License.         #
# You may obtain a copy of the License at                                  #
#                                                                          #
#     http:#www.apache.org/licenses/LICENSE-2.0                            #
#                                                                          #
# Unless required by applicable law or agreed to in writing, software      #
# distributed under the License is distributed on an "AS IS" BASIS,        #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. #
# See the License for the specific language governing permissions and      #
# limitations under the License.                                           #
############################################################################

version: '3.5'

networks:
  mynet1:
    name: mynet1

volumes:
  elasticsearch-data:
    driver: local
  fluentd-logs:
    driver: local
  cassandra-data:
    driver: local
  cassandra-logs:
    driver: local
  postgres-data:
    driver: local
  postgres-logs:
    driver: local
  rabbitmq-data:
    driver: local
  app-logs:
    driver: local


services:

  elasticsearch:
    image: elasticsearch:7.13.2
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    expose:
      - "9200"
    ports:
      - "9200:9200"
    networks:
      - mynet1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    restart: unless-stopped

  kibana:
    image: kibana:7.13.2
    container_name: kibana
    hostname: kibana
    ports:
      - "5601:5601"
    networks:
      - mynet1
    environment:
      - ELASTICSEARCH_HOSTS="http://elasticsearch:9200"
    restart: unless-stopped
    depends_on:
      - "elasticsearch"
      

  fluentd:
    build:
      context: ./fluentd
      dockerfile: Dockerfile
    image: ntw/fluentd
    container_name: fluentd
    hostname: fluentd
    networks:
      - mynet1
    ports:
      - "24224:24224"
    volumes:
      - ${PWD}/fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - fluentd-logs:/fluentd/log
    depends_on:
      - "elasticsearch"
    restart: unless-stopped


  jaeger-agent:
    image: jaegertracing/jaeger-agent:1.42
    container_name: jaeger-agent
    hostname: jaegar-agent
    networks:
      - mynet1
    ports:
      - "6831:6831/udp"
      - "14271:14271"
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    command: ["--reporter.grpc.host-port=jaeger-collector:14250"]
    restart: unless-stopped
    depends_on:
      - "jaeger-collector"

  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.42
    container_name: jaeger-collector
    hostname: jaegar-collector
    networks:
      - mynet1
    ports:
      - "14250:14250"
      - "14269:14269"
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
#      - ES_SERVER_URLS="elasticsearch:9200"
    command: [
      "--es.server-urls=http://elasticsearch:9200",
      "--es.num-shards=1",
      "--es.num-replicas=0",
      "--log-level=error"
    ]
    restart: unless-stopped
    
  jaeger-query:
    image: jaegertracing/jaeger-query:1.42
    container_name: jaeger-query
    hostname: jaeger-query
    networks:
      - mynet1
    ports:
      - "16685:16685"
      - "16686:16686"
      - "16687:16687"
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    command: [
      "--es.server-urls=http://elasticsearch:9200",
      "--span-storage.type=elasticsearch",
      "--log-level=debug"
    ]
    restart: unless-stopped
    depends_on:
      - "jaeger-collector"

  prometheus:
    image: prom/prometheus:v2.42.0
    container_name: prometheus
    hostname: prometheus
    networks:
      - mynet1
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ${PWD}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PWD}/prometheus/rules.yml:/etc/prometheus/rules.yml
    restart: unless-stopped

  es-exporter:
    image: prometheuscommunity/elasticsearch-exporter:v1.5.0
    container_name: es-exporter
    hostname: es-exporter
    networks:
      - mynet1
    ports:
      - "9114:9114"
    command:
      - '--es.uri=http://elasticsearch:9200'
    restart: unless-stopped

  pg-exporter:
    image: prometheuscommunity/postgres-exporter:v0.11.1
    container_name: pg-exporter
    hostname: pg-exporter
    networks:
      - mynet1
    ports:
      - "9187:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:postgres@postgres:5432/oms?sslmode=disable
    restart: unless-stopped

  redis-exporter:
    image: oliver006/redis_exporter:v1.47.0
    container_name: redis-exporter
    hostname: redis-exporter
    networks:
      - mynet1
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis://redis:6379
    restart: unless-stopped

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    image: ntw/postgres
    container_name: postgres
    hostname: postgres
    networks:
      - mynet1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-logs:/var/log/postgresql
      - postgres-data:/var/lib/postgresql/data
    command: postgres -c shared_buffers=128MB -c max_connections=50


  cassandra:
    build:
      context: ./cassandra
      dockerfile: Dockerfile
    image: ntw/cassandra
    container_name: cassandra
    hostname: cassandra
    networks:
      - mynet1
    ports:
      - "9042:9042"
      - "7070:7070"
    environment:
      - JVM_OPTS=-Xms512M -Xmx1024M
      - SCHEMA_SEED_INSTANCE=cassandra
    volumes:
      - cassandra-logs:/var/log/cassandra
      - cassandra-data:/var/lib/cassandra
    entrypoint: /docker-entrypoint-second.sh


  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    hostname: rabbitmq
    networks:
      - mynet1
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq"

  redis:
    image: redis:7.0
    container_name: redis
    hostname: redis
    networks:
      - mynet1
    ports:
      - "6379:6379"


  eureka:
    build:
      context: ./eureka
      dockerfile: Dockerfile
    image: ntw/eureka
    container_name: eureka
    hostname: eureka
    networks:
      - mynet1
    ports:
      - "8761:8761"
    env_file: .env
    environment:
      - JAVA_OPTIONS=-Xmx512M
      - server.port=8761
      - eureka.client.registerWithEureka=false
      - eureka.client.fetchRegistry=false
    volumes:
      - app-logs:/usr/local/tomcat/logs


  lb-web:
    build:
      context: ./lb-web
      dockerfile: Dockerfile
    image: ntw/lb-web
    container_name: lb-web
    networks:
      - mynet1
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SERVER_HOSTS=web
      - SERVER_PORT=8000
      - USE_SSL=false
    volumes:
      - app-logs:/var/log/oms
    depends_on:
      - "web"


  lb-services:
    build:
      context: ./lb-services
      dockerfile: Dockerfile
    image: ntw/lb-services
    container_name: lb-services
    networks:
      - mynet1
    ports:
      - "81:80"
    environment:
      - SERVER_HOSTS=gateway-svc
      - SERVER_PORT=8080
    volumes:
      - app-logs:/var/log/oms
    depends_on:
      - "gateway-svc"


  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: ntw/web
    container_name: web
    hostname: web
    networks:
      - mynet1
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - app-logs:/var/log/oms
    #command: python3 manage.py runserver 0.0.0.0:8000
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "127.0.0.1:24224"
        tag: web
    depends_on:
      - "fluentd"


  services:
    build:
      context: ./services
      dockerfile: Dockerfile
    image: ntw/services
    container_name: services-build


  gateway-svc:
    image: ntw/services
    container_name: gateway-svc
    hostname: gateway-svc
    networks:
      - mynet1
    ports:
      - "8080:8080"
      - "6000:6005"
    env_file: .env
    environment:
      - eureka.instance.hostname=gateway-svc
      - server.threadPool.threads.maximum=20
    volumes:
      - app-logs:/var/log/oms
    entrypoint: /usr/bin/docker-entrypoint.sh gateway
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "127.0.0.1:24224"
        tag: gateway-svc
    depends_on:
      - "fluentd"

  admin-svc:
    image: ntw/services
    container_name: admin-svc
    hostname: admin-svc
    networks:
      - mynet1
    ports:
      - "8081:8080"
      - "6001:6005"
    env_file: .env 
    environment:
      - eureka.instance.hostname=admin-svc
    volumes:
      - app-logs:/var/log/oms
    entrypoint: /usr/bin/docker-entrypoint.sh admin
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "127.0.0.1:24224"
        tag: admin-svc
    depends_on:
      - "fluentd"

  auth-svc:
    image: ntw/services
    container_name: auth-svc
    hostname: auth-svc
    networks:
      - mynet1
    ports:
      - "8082:8080"
      - "6002:6005"
    env_file: .env 
    environment:
      - eureka.instance.hostname=auth-svc
    volumes:
      - app-logs:/var/log/oms
    entrypoint: /usr/bin/docker-entrypoint.sh auth
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "127.0.0.1:24224"
        tag: auth-svc
    depends_on:
      - "fluentd"

  product-svc:
    image: ntw/services
    container_name: product-svc
    hostname: product-svc
    networks:
      - mynet1
    ports:
      - "8083:8080"
      - "6003:6005"
    env_file: .env 
    environment:
      - eureka.instance.hostname=product-svc
    volumes:
      - app-logs:/var/log/oms
    entrypoint: /usr/bin/docker-entrypoint.sh product
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "127.0.0.1:24224"
        tag: product-svc
    depends_on:
      - "fluentd"

  order-svc:
    image: ntw/services
    container_name: order-svc
    hostname: order-svc
    networks:
      - mynet1
    ports:
      - "8084:8080"
      - "6004:6005"
    env_file: .env 
    environment:
      - eureka.instance.hostname=order-svc
    volumes:
      - app-logs:/var/log/oms
    entrypoint: /usr/bin/docker-entrypoint.sh order
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "127.0.0.1:24224"
        tag: order-svc
    depends_on:
      - "fluentd"
      - "rabbitmq"

  inventory-svc:
    image: ntw/services
    container_name: inventory-svc
    hostname: inventory-svc
    networks:
      - mynet1
    ports:
      - "8085:8080"
      - "6005:6005"
    env_file: .env 
    environment:
      - eureka.instance.hostname=inventory-svc
    volumes:
      - app-logs:/var/log/oms
    entrypoint: /usr/bin/docker-entrypoint.sh inventory
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "127.0.0.1:24224"
        tag: inventory-svc
    depends_on:
      - "fluentd"


  spa:
    build:
      context: ./spa
      dockerfile: Dockerfile
    image: ntw/spa
    container_name: spa
    hostname: spa
    networks:
      - mynet1
    ports:
      - "3000:80"
    env_file: .env
    volumes:
      - app-logs:/var/log/oms
