---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: service
  labels:
    app: auth-svc
  annotations:
    service.kubernetes.io/topology-aware-hints: auto
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: auth-svc
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-svc-pods
  namespace: service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-svc
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 25%
       maxSurge: 1
  template:
    metadata:
      labels:
        app: auth-svc
    spec:
      initContainers:
      - name: wait-for-postgres
        image: postgres
        command: [ '/bin/bash','-c', 'until pg_isready -h postgres.data; do echo waiting for postgres; sleep 2; done;' ]
      - name: wait-for-cassandra
        image: cassandra
        command: [ '/bin/bash','-c', 'until echo exit | cqlsh cassandra.data; do echo waiting for cassandra; sleep 5; done;' ]
      containers:
      - name: auth-svc-cont
        image: IMAGE_REGISTRY_PATH/services:REVISION_ID
        args: ["auth"]
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: log-data
            mountPath: /var/log/oms
        envFrom:
          - configMapRef:
              name: service-config
        env:
          - name: database.type
            value: CQL
        livenessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 2
      volumes:
        - name: log-data
          emptyDir: {}
      topologySpreadConstraints:                                                                                                                     
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: auth-svc
