---
apiVersion: v1
kind: Service
metadata:
  name: spa-app
  namespace: ui
  labels:
    app: spa-app
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32105
  selector:
    app: spa-app
#  type: LoadBalancer
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spa-app-pods
  namespace: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spa-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 25%
       maxSurge: 1
  template:
    metadata:
      labels:
        app: spa-app
    spec:
      containers:
      - name: spa-app-cont
        image: IMAGE_REGISTRY_PATH/spa:REVISION_ID
        imagePullPolicy: Always
        ports:
          - containerPort: 80      
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 2
