---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: monitor
  labels:
    app: jaeger-agent
spec:
  clusterIP: None
  ports:
    - port: 14271
      protocol: TCP
      name: tcp
    - port: 6831
      protocol: UDP
      name: udp
  selector:
    app: jaeger-agent
    
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jaeger-agent-pods
  namespace: monitor
  labels:
    app: jaeger-agent
spec:
  selector:
    matchLabels:
      app: jaeger-agent
  template:
    metadata:
      labels:
        app: jaeger-agent
    spec:
      containers:
      - name: jaeger-agent-cont
        image: jaegertracing/jaeger-agent:REVISION_ID
        ports:
          - protocol: TCP
            containerPort: 14271
            name: tcp
          - protocol: UDP
            containerPort: 6831
            name: udp
        env:
          - name: SPAN_STORAGE_TYPE
            value: "elasticsearch"
        args: ["--reporter.grpc.host-port=jaeger-collector:14250"]
        livenessProbe:
          tcpSocket:
            port: 14271
          initialDelaySeconds: 120
        readinessProbe:
          tcpSocket:
            port: 14271
          initialDelaySeconds: 30
          periodSeconds: 2


---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: monitor
  labels:
    app: jaeger-collector
spec:
  clusterIP: None
  ports:
    - port: 14250
      name: default
  selector:
    app: jaeger-collector
---
apiVersion: v1
kind: Pod
metadata:
  name: jaeger-collector-pod
  namespace: monitor
  labels:
    app: jaeger-collector
spec:
  initContainers:
  - name: wait-for-elasticsearch
    image: curlimages/curl
    command: ['sh', '-c', 'until curl http://elasticsearch:9200; do echo Waiting for ES; sleep 2; done;']
  containers:
    - name: jaeger-collector-cont
      image: jaegertracing/jaeger-collector:latest
      imagePullPolicy: Always
      ports:
        - protocol: TCP
          containerPort: 14250
      env:
        - name: SPAN_STORAGE_TYPE
          value: "elasticsearch"
      args: [
        "--es.server-urls=http://elasticsearch:9200",
        "--es.num-shards=1",
        "--es.num-replicas=0",
        "--log-level=error"
      ]
      livenessProbe:
        tcpSocket:
          port: 14250
        initialDelaySeconds: 120
      readinessProbe:
        tcpSocket:
          port: 14250
        initialDelaySeconds: 30
        periodSeconds: 2


---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: monitor
  labels:
    app: jaeger-query
spec:
  ports:
    - name: ui
      protocol: TCP
      port: 16686
      targetPort: 16686
      nodePort: 32102
    - name: exporter
      protocol: TCP
      port: 16687
      targetPort: 16687
  selector:
    app: jaeger-query
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: jaeger-query-pod
  namespace: monitor
  labels:
    app: jaeger-query
spec:
  initContainers:
  - name: wait-for-elasticsearch
    image: curlimages/curl
    command: ['sh', '-c', 'until curl http://elasticsearch:9200; do echo Waiting for ES; sleep 2; done;']
  containers:
    - name: jaeger-query-cont
      image: jaegertracing/jaeger-query:latest
      imagePullPolicy: Always
      ports:
        - protocol: TCP
          containerPort: 16686
      env:
        - name: SPAN_STORAGE_TYPE
          value: "elasticsearch"
      args: [
        "--es.server-urls=http://elasticsearch:9200",
        "--span-storage.type=elasticsearch",
        "--log-level=debug"
      ]
      livenessProbe:
        httpGet:
          path: /
          port: 16686
        initialDelaySeconds: 120
      readinessProbe:
        httpGet:
          path: /
          port: 16686
        initialDelaySeconds: 30
        periodSeconds: 2
