version: '3.5'

networks:
  mynet1:
    name: mynet1

volumes:
  postgres-data:
    driver: local
  postgres-logs:
    driver: local
  app-logs:
    driver: local


services:

  web:
    build:
      context: ../../web
      dockerfile: Dockerfile
    image: ntw/web
    container_name: web
    hostname: web
    networks:
      - mynet1
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file: .env
    volumes:
      - app-logs:/var/log/oms

      
  services:
    build:
      context: ../../services
      dockerfile: Dockerfile
    image: ntw/services
    container_name: services-build

  admin-svc:
    image: ntw/services
    container_name: admin-svc
    hostname: admin-svc
    networks:
      - mynet1
    ports:
      - "8081:8080"
    command: admin
    env_file: .env
    volumes:
      - app-logs:/var/log/oms

  auth-svc:
    image: ntw/services
    container_name: auth-svc
    hostname: auth-svc
    networks:
      - mynet1
    ports:
      - "8082:8080"
    command: auth
    env_file: .env
    volumes:
      - app-logs:/var/log/oms

  product-svc:
    image: ntw/services
    container_name: product-svc
    hostname: product-svc
    networks:
      - mynet1
    ports:
      - "8083:8080"
    command: product
    env_file: .env
    volumes:
      - app-logs:/var/log/oms

  order-svc:
    image: ntw/services
    container_name: order-svc
    hostname: order-svc
    networks:
      - mynet1
    ports:
      - "8084:8080"
    command: order
    env_file: .env
    volumes:
      - app-logs:/var/log/oms

  inventory-svc:
    image: ntw/services
    container_name: inventory-svc
    hostname: inventory-svc
    networks:
      - mynet1
    ports:
      - "8085:8080"
    command: inventory
    env_file: .env
    volumes:
      - app-logs:/var/log/oms


  spa:
    build:
      context: ../../spa
      dockerfile: Dockerfile
    image: ntw/spa
    container_name: spa
    hostname: spa
    networks:
      - mynet1
    ports:
      - "3000:80"


  postgres:
    build:
      context: ../../postgres
      dockerfile: Dockerfile
    image: ntw/postgres
    container_name: postgres
    hostname: postgres
    networks:
      - mynet1
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - postgres-logs:/var/log/postgresql
      - postgres-data:/var/lib/postgresql/data


